//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace Nujit.NujitERP.NujitWebService {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UpdateServiceSoap", Namespace="http://www.nujit.com/")]
    public class UpdateService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public UpdateService() {
            this.Url = "http://nujit.com/nujit_webservice/webservice/updateService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nujit.com/CheckForUpdate", RequestNamespace="http://www.nujit.com/", ResponseNamespace="http://www.nujit.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("updateAvailable")]
        public bool CheckForUpdate(string clientVersion, out string updateUrl) {
            object[] results = this.Invoke("CheckForUpdate", new object[] {
                        clientVersion});
            updateUrl = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCheckForUpdate(string clientVersion, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CheckForUpdate", new object[] {
                        clientVersion}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndCheckForUpdate(System.IAsyncResult asyncResult, out string updateUrl) {
            object[] results = this.EndInvoke(asyncResult);
            updateUrl = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nujit.com/CheckForUpdateERP", RequestNamespace="http://www.nujit.com/", ResponseNamespace="http://www.nujit.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("updateAvailable")]
        public bool CheckForUpdateERP(string clientVersion, string companyName, out string updateUrl) {
            object[] results = this.Invoke("CheckForUpdateERP", new object[] {
                        clientVersion,
                        companyName});
            updateUrl = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCheckForUpdateERP(string clientVersion, string companyName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CheckForUpdateERP", new object[] {
                        clientVersion,
                        companyName}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndCheckForUpdateERP(System.IAsyncResult asyncResult, out string updateUrl) {
            object[] results = this.EndInvoke(asyncResult);
            updateUrl = ((string)(results[1]));
            return ((bool)(results[0]));
        }
    }
}
